# becomes PLATFORM=X64|X86 environment variable (note uppercase!)
platform:
  - x64
  - x86

# becomes CONFIGURATION=Debug|Release environment variable
configuration:
  - Debug
  - Release

environment:
  global:
    BUILD_LENSTOOL: 'OFF'
    BUILD_STATIC: 'OFF'
  matrix:
    # VS 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_INIT_CMD: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      GENERATOR: Visual Studio 14 2015

    # VS 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_INIT_CMD: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      GENERATOR: Visual Studio 15 2017
      
    # VS 2019
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_INIT_CMD: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
      GENERATOR: Visual Studio 16 2019

    # VS 2019 (with lenstool and static libraries)
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_INIT_CMD: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
      GENERATOR: Visual Studio 16 2019
      BUILD_LENSTOOL: 'ON'
      BUILD_STATIC: 'ON'

install:
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=true

  # Select Visual Studio version and architecture
  - call "%VS_INIT_CMD%" %PLATFORM%
  - if /I %PLATFORM% == x86 ( set GENERATOR_PLATFORM=Win32 )
  - if /I %PLATFORM% == x64 ( set GENERATOR_PLATFORM=x64 )

  # Print environment variables
  - set

  # Update vcpkg
  # https://help.appveyor.com/discussions/problems/24684-problem-with-vcpkg-wrong-version-on-appveyor
  - powershell iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/build-images/master/scripts/Windows/install_vcpkg.ps1'))
  
  # Install dependencies
  - vcpkg install glib:%PLATFORM%-windows
  - if %BUILD_LENSTOOL% == ON ( vcpkg install libpng:%PLATFORM%-windows )
  # xmllint tool for tests
  - choco install xsltproc

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "%GENERATOR%" -A %GENERATOR_PLATFORM% -DBUILD_STATIC=%BUILD_STATIC% -DBUILD_LENSTOOL=%BUILD_LENSTOOL% -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX=install -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DGLIB2_BASE_DIR=c:/tools/vcpkg/installed/%PLATFORM%-windows
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --target install

test_script:
  - ctest -C %CONFIGURATION% --output-on-failure

cache: c:\tools\vcpkg\installed\